on:
  push:
    tags:
      - 'v*'
    branches:
      - '**'

jobs:

  build:
    name: ${{ matrix.OS }}

    strategy:
      matrix:
        OS:
        - macos-13  # Intel
        - macos-14  # M1
        - ubuntu-24.04
        - ubuntu-22.04
        - ubuntu-20.04
    runs-on: ${{ matrix.OS }}

    # NOTE: PWD = GITHUB_WORKSPACE = /home/runner/work/cl-repl/cl-repl = ~/work/cl-repl/cl-repl
    #       HOME = /home/runner

    steps:

    - uses: actions/checkout@v4

    - name: Install SBCL (macOS)
      if: startsWith(matrix.OS, 'macos')
      run: brew install sbcl

    - name: Install SBCL (Ubuntu)
      if: startsWith(matrix.OS, 'ubuntu')
      run: sudo apt install sbcl

    - name: Install quicklisp
      run: |
        wget https://beta.quicklisp.org/quicklisp.lisp
        echo -ne '\n' | \
        sbcl --load quicklisp.lisp \
             --eval '(quicklisp-quickstart:install)' \
             --eval '(ql:add-to-init-file)' \
             --quit

    - name: Dump lisp image
      run: |
        sbcl --load cl-repl.asd \
             --eval '(ql:quickload :cl-repl)' \
             --eval '(asdf:make :cl-repl)' \
             --quit

    - name: Rename lisp image
      run: |
        mv cl-repl ~/cl-repl.${{matrix.OS}}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: cl-repl.${{ matrix.OS }}
        path: ~/cl-repl.${{ matrix.OS }}

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: ~/cl-repl.${{ matrix.OS }}
