on: [push, pull_request]

jobs:

  build:

    name: ${{ matrix.OS }}

    runs-on: windows-latest

    strategy:
      matrix:
        lisp: [sbcl_static]
        OS: [windows]

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v4

    - uses: msys2/setup-msys2@v2
      with:
        install: git curl zip mingw-w64-x86_64-readline mingw-w64-x86_64-ncurses mingw-w64-x86_64-toolchain mingw-w64-x86_64-autotools


    - name: Check $PATH
      run: echo $PATH

    - name: Download implementation
      env:
        LISP: ${{ matrix.lisp }}
        OS:   ${{ matrix.OS }}
      run: |
        pwd
        ls -l
        bash --version
        bash <(curl -s https://raw.githubusercontent.com/digikar99/lisp-travis-lite/master/run.sh)

    - name: Statically link against libreadline
      run: |
        # Turns out we also need other libraries
        SBCL_DIR="sbcl-2.6.2+r00-x86-64-windows"
        cd "/home/runneradmin/$SBCL_DIR"
        LIBREADLINE="/mingw64/lib/libreadline.a"
        LIBNCURSES="/mingw64/lib/libncurses.a"
        LIBWINPTHREAD="/mingw64/lib/libwinpthread.a"
        export WHOLE_ARCHIVES="$LIBNCURSES $LIBREADLINE -Wl,--no-whole-archive $LIBWINPTHREAD"
        make -C "src/runtime" -f binaries.mk sbcl.extras
        mv "src/runtime/sbcl.extras" "src/runtime/sbcl"


    - name: Dump lisp image (windows)
      run: |
        cl --load cl-repl.asd \
           --eval '(ql:quickload :cl-repl)' \
           --eval "(cffi:close-foreign-library 'rl:readline)"\
           --eval '(asdf:make :cl-repl)' \
           --quit

    - name: Set release name
      run: |
        echo "CL_REPL_DIR=cl-repl.${{ matrix.OS }}.$(uname -m)" >> $GITHUB_ENV

    - name: Rename lisp image and copy licenses
      run: |
        mkdir ${{ env.CL_REPL_DIR }}
        mv cl-repl.exe ${{ env.CL_REPL_DIR }}/${{ env.CL_REPL_DIR }}.exe
        cp -r /home/runneradmin/sbcl-2.6.2+r00-x86-64-windows/COPYING* ${{ env.CL_REPL_DIR }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.CL_REPL_DIR }}
        path: ${{ env.CL_REPL_DIR }}
        compression-level: 0

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: ${{ env.CL_REPL_DIR }}.zip
